import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import ClientLayout from './clientLayout'; 

const myFont = localFont({ src: '../assets/font/static/DMSans_18pt-Regular.ttf' });

export const metadata: Metadata = {
  title: "Yustore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
